# permissions for end users to edit curios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curio-editor-role
rules:
- apiGroups:
  - server.psc.bb.com.br
  resources:
  - curios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - server.psc.bb.com.br
  resources:
  - curios/status
  verbs:
  - get
