# permissions for end users to view curios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curio-viewer-role
rules:
- apiGroups:
  - server.psc.bb.com.br
  resources:
  - curios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - server.psc.bb.com.br
  resources:
  - curios/status
  verbs:
  - get
